[project]
name = "faisalahmedresume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudpickle>=3.0.0",
    "pip>=25.1.1",
    "pydantic>=2.11.7",
    "streamlit==1.47.0",
    "streamlit-extras>=0.7.5",
]
